config/routes.rb
ChennaiFloods::Application.routes.draw do

  get "posts/index"

  get "posts/show"

  get "post/home"

  get "home/index"

  get "posts/refresh"

  get "posts/location"

  get "posts/needpage"

  get "posts/supplypage"

  resources :posts
  
  

  root :to => 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  #include PgSearch
  attr_accessible :action, :feedText, :location, :materials, :url, :source, :twitter_html

=begin
  def self.getAllSupplies
  	Post.where("action = ?", 0)
  end

  def self.getAllDemands
  	Post.where("action = ?", 1)
  end
=end
=begin
  def self.getDemandsByMaterial(material)
  	Post.where("action = ? AND material LIKE ?", 1, material)
  end

  def self.getSuppliesByMaterial(material)
  	Post.where("action = ? AND material LIKE ?", 0, material)
  end
=end

  def self.getAll()
    Post.select('DISTINCT ON (url,created_at) *').where("created_at > (NOW() - INTERVAL '48 hour')").order('created_at DESC')
  end

  def self.getByLocation(location)
    l = '%' + location + '%'
    Post.select('DISTINCT ON (url,created_at) *').where("location ilike ? and created_at > (NOW() - INTERVAL '48 hour')", l).order('created_at DESC')
  end

  def self.getByLocations(locations)
    location = locations.join(' | ')
    Post.select('DISTINCT ON (url,created_at) *').where("to_tsvector('english', location) @@ plainto_tsquery('english', ?) and created_at > (NOW() - INTERVAL '48 hour')",location).order('created_at DESC')
    #Post.where()
  end

  def self.getByMaterials(materials)
    puts materials
    material = materials.join(' | ')
    Post.select('DISTINCT ON (url,created_at) *').where("to_tsvector('english', materials) @@ plainto_tsquery('english', ?) and created_at > (NOW() - INTERVAL '48 hour')",material).order('created_at DESC')
  end

  def self.getByMaterial(material)
    material = '%' + material + '%'
    #puts material
    Post.select('DISTINCT ON (url,created_at) *').where("materials ilike ? and created_at > (NOW() - INTERVAL '48 hour')", material).order('created_at DESC')
  end

  def self.getByLocationsAndMaterials(locations, materials)
    location = locations
    material = materials.join(' | ')
    Post.select('DISTINCT ON (url,created_at) *').where("to_tsvector('english', location) @@ plainto_tsquery('english', ?) AND
                to_tsvector('english', materials) @@ plainto_tsquery('english', ?) and created_at > (NOW() - INTERVAL '48 hour')",
                location, material).order('created_at DESC')
  end
end

app/controllers/application_controller.rb
require 'will_paginate/array'
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
require 'set'
class PostsController < ApplicationController
  respond_to :js
  
	def index
		@locations = Set.new
		@materials = Set.new
		@loc_count = Hash.new(0)
		@materials.add?("All")
		@posts = Post.getAll
		#puts @posts
		#@locations = Set.new
		#@materials = Set.new
		session[:material] = 'All'
		@posts.each do |post|
			if post.location != nil
				#puts post.location.split(',')
				ls = post.location.split(',')
				ls.each do |l|
					l = l.strip
					@loc_count[l]+=1
					if !@locations.include?(l)
						@locations.add?(l)
					end
				end
			end
            
            @sel_location = 'All Places'

			if post.materials == nil
				next
			end

			#puts post.materials.split(',')
			ms = post.materials.split(',')
			ms.each do |m|
				m = m.strip
				if !@materials.include?(m)
					@materials.add?(m)
				end
			end
			@materials
		end
        
		separate_demand_supply
	end

	def needpage
	    @demand = Post.select('DISTINCT ON (url) *').where("action=0").paginate(:page => params[:page], :per_page => 50)
	    respond_to do |format|
	    	format.js
	    end
	end

	def supplypage
	    @supply = Post.select('DISTINCT ON (url) *').where("action=1").paginate(:page => params[:page], :per_page => 50)
	    respond_to do |format|
	    	format.js
	    end
	end

	def location
		puts "PARAMS " 
		puts params
		material = session[:material]
		puts material
		materials = []
		materials <<  material
		#materials.delete_at(0)
		location = params[:format]
		if location == nil
			location = 'All'
		end

		@sel_location = location

        query materials, location
	end

	def refresh
		material = params[:post][:materials]
		materials = []
		materials <<  material
		#materials.delete_at(0)
		location = params[:post][:commit]
		@key = location
		if location == nil || location == 'GO'
			location = 'All'
		end
        session[:material] = material
        query materials, location
	end

	def query(materials, location)
		#material = params[:material]
		#location = params[:location]
		material = materials[0]
		@posts = []
		#if materials.index("All") == nil
		#	material = 'not_all'
		#end

		if material != 'All' && location != 'All'
			@posts = Post.getByLocationsAndMaterials(location, materials)
		elsif material == 'All' && location != 'All'
			@posts = Post.getByLocation(location)
		elsif material != 'All' && location == 'All'
			@posts = Post.getByMaterial(material)
		else
			index
		end

		@locations = Set.new
		@loc_count = Hash.new(0)

		@posts.each do |post|
			#next if post.location == nil
			#puts post.location.split(',')
			if post.location != nil
				ls = post.location.split(',')
				ls.each do |l|
					l = l.strip
					@loc_count[l]+=1
					if !@locations.include?(l)
						@locations.add?(l)
					end
				end
			end
		end

		separate_demand_supply
	end

	def create
		post = Post.new
		post.action = params[:action]
		post.feedText = params[:feedText]
		post.location = params[:locations]
		post.materials = params[:materials]
		post.save
	end

	private 

	def separate_demand_supply
		@demand = []
		@supply = []
		#puts @posts.count
		@posts.each do |post|
			#puts post
			if post.action == 0
				@demand << post
			else
				@supply << post
			end
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<div id="form">
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head prefix="og: http://ogp.me/ns#">
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  
  <%= stylesheet_link_tag "application", 'data-turbolinks-track' => true, :media => "all" %>
  <%= javascript_include_tag "application" %>
  <link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon"> 
  <link rel="icon" href="assets/favicon.ico" type="image/x-icon">
  <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <script src="//connect.facebook.net/en_US/sdk.js#xfbml=1&amp;version=v2.2" 
                async></script> 
  <script src="https://platform.twitter.com/widgets.js"></script>

  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-71297654-1', 'auto');
  ga('send', 'pageview');
</script>             
  <%= csrf_meta_tags %>
        
<title>Save the Volunteer</title>

<meta property="og:description" content= "Do you know how Chennai got more volunteers than victims?" />
<meta property="og:title" content= "Save the Volunteer from Crocodiles ;)" />
<meta property="og:image:type" content="image/png">
<meta property="og:image:height" content="200" />
<meta property="og:image:width" content="200" />
<meta property="og:image" content= "http://savethevolunteer.com/assets/image01.png" />
<meta property="og:image:url" content= "http://savethevolunteer.com/assets/image01.png" />
<meta property="og:url" content= "http://www.savethevolunteer.com" />

</head>
<body>

<%= yield %>

<script type="text/javascript" src="http://assets.freshdesk.com/widget/freshwidget.js"></script>
<script type="text/javascript">
  FreshWidget.init("", {"queryString": "&widgetType=popup&formTitle=Tell+us+how+we+can+improve+this&submitThanks=Thank+you+for+the+message!+We+will+try+to+get+back+soon.&searchArea=no", "utf8": "✓", "widgetType": "popup", "buttonType": "text", "buttonText": "Talk to us", "buttonColor": "white", "buttonBg": "#006063", "alignment": "1", "offset": "75%", "submitThanks": "Thank you for the message! We will try to get back soon.", "formHeight": "300px", "url": "https://freshiq.freshdesk.com"} );
</script>
</body>
</html>

app/views/posts/_citypartial.html.erb
<% @loc_count.sort.map do |location,count| %>

	<%= link_to posts_location_path(location), remote: true do %>
	<button class="btn btn-default btn-xs butn-hide"><%= location %> <span class="badge"><%= count %></span></button>
  <% end %>

<% end %>

app/views/posts/_needpartial.html.erb
<% @demand.first(100).each do |post| %>
        <% if post.source == 0 %>
              <div class="fb-post mb30" 
                data-href="<%= post.url %>"
        data-width="100%"></div>
        <% elsif post.source == 2 %>
          <%=  post.twitter_html.html_safe %>
        </br>     
        <% else %>
            <ul class="media-list">
              <li class="media">
                <div class="media-body"> 
                  <span class="text-muted pull-right"> 
                    <small class="text-muted">
                      <%= time_ago_in_words(post.created_at) %> ago
                    </small> 
                  </span> 
                  <% if post.location != nil %>
                  <strong><%= post.location%></strong>
                  <%end%>
                  <% materials = post.materials.split(',') %>
                  <p>
                  <% materials.each do |material| %>
                  <span class="label label-info"><%= material%></span>&nbsp;
                  <%end%>
                </p>
                  <p> <%= post.feedText %> </p>
                  <a href="<%= post.url %>" target="_blank"><%= post.url %> </a>
                </div>
              </li>
            </ul>
       <% end %>

<% end %>

app/views/posts/_supplypartial.html.erb
<% @supply.first(100).each do |post| %>
        <% if post.source == 0 %>
              <div class="fb-post" 
                data-href="<%= post.url %>"
        data-width="500"></div>
      </br>
        <% elsif post.source == 2 %>
        <%=  post.twitter_html.html_safe %>
        </br>     
        <% else %>  
            <ul class="media-list">
              <li class="media">
                <div class="media-body"> <span class="text-muted pull-right"> <small class="text-muted"><%= time_ago_in_words(post.created_at) %> ago</small> </span> 
                  <strong><%= post.location%></strong>
                  <p>
                  <% materials = post.materials.split(',') %>
                  <% materials.each do |material| %>
                  <span class="label label-info"><%= material%></span>&nbsp;
                  <%end%>
                </p>
                  <p> <%= post.feedText %> </p>
                  <a href="<%= post.url %>" target="_blank"><%= post.url %> </a>
                </div>
              </li>
            </ul>
       <% end %>

<% end %>

app/views/posts/index-4.html.erb
  <body>
    <nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Chennai Flood Relief</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!-- /.nav-collapse -->
      </div><!-- /.container -->
    </nav><!-- /.navbar -->

    <div class="container" ng-init="tab = 2">

      <div class="row row-offcanvas row-offcanvas-right">
        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar">
          <div class="list-group" >
          <a href ng-class="{active:tab == 1}" ng-click="tab = 1" class="list-group-item">Availability</a>
          <a href ng-class="{active:tab == 2}" ng-click="tab = 2" class="list-group-item">Needs</a>
          </div>
          <br>
          <br>
          <h4 class="checkbox">Select Places</h4>
          <div class="checkbox">
            <label><input type="checkbox" value="" ng-model="checkbox.value">Porur</label>
          </div>
          <div class="checkbox">
            <label><input type="checkbox" value="" nd-model="checkbox.value">Velachery</label>
          </div>
          <div class="checkbox">
            <label><input type="checkbox" value=""> Ekaduthaangal</label>
          </div>
          {{checkbox.value}}
        </div><!--/.sidebar-offcanvas-->

        <div class="col-xs-12 col-sm-9">
          <!--<p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
          </p>
          <div class="jumbotron">
            <h1>Hello, world!</h1>
            <p>This is an example to show the potential of an offcanvas layout pattern in Bootstrap. Try some responsive-range viewport sizes to see it in action.</p>
          </div>-->
          <div class="row" >
            <div class="col-xs-6 col-lg-4" id="demands" ng-show="tab === 2">
              <% @demands.each do |demand| %>
              <h3>@<%= demand.location %></h3>
                <ul>
                <% demand.materials.split(' ').each do |material| %>
                  <li> <%= material %> </li>
                </ul>
                <% end %>
              <% end %>
            </div><!--/.col-xs-6.col-lg-4-->
            <div class="col-xs-6 col-lg-4" id="demands" ng-show="tab === 1">
              <% @supplies.each do |supply| %>
              <h3>@<%= supply.location %></h3>
                <ul>
                <% supply.materials.split(' ').each do |material| %>
                  <li> <%= material %> </li>
                </ul>
                <% end %>
              <% end %>
            </div><!--/.col-xs-6.col-lg-4-->
            <!--<div class="col-xs-6 col-lg-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
            </div><!--/.col-xs-6.col-lg-4-->
            <!--<div class="col-xs-6 col-lg-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
            </div><!--/.col-xs-6.col-lg-4-->
            <!--<div class="col-xs-6 col-lg-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
            </div><!--/.col-xs-6.col-lg-4-->
            <!--<div class="col-xs-6 col-lg-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
            </div><!--/.col-xs-6.col-lg-4-->
            <!--<div class="col-xs-6 col-lg-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
            </div><!--/.col-xs-6.col-lg-4-->
          </div><!--/row-->
        </div><!--/.col-xs-12.col-sm-9-->

        
      </div><!--/row-->

      <hr>

      <footer>
        <p>&copy; 2015 FloodRelief</p>
      </footer>

    </div><!--/.container-->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
    <script src="offcanvas.js"></script>
  </body>
</html>

app/views/posts/index.html.erb
<div id="wrapper" class="">
<div id="page-content-wrapper">
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header"><img class="logo" src="assets/image01.png" /><a class="navbar-brand">Save the Volunteer<br/><span>from outdated &amp; false messages</span></a></div>
    </div>
  </nav>
  <div class="container-fluid mainCtd-1" id="colMain">
    <div class="row searchBar">
     <div class="col-md-2">
       <div class="row">      
       <div id="colPush" class="lftBar-0 col-md-12">
       </br></br></br>
       <h5>Browse by Areas</h5>
      <div id="city_div">
        <%= render :partial => 'citypartial' %></div>
        </div>   
      </div>
     </div>

      <div class="col-md-10 choose-items">
      <h4>Looking for</h4>
      <%= form_for :post, :url => posts_refresh_path, :method => :get, remote: true do |f| %>

        <%= f.select(:materials, options_for_select(@materials.sort), {}, {multiple: false, class: 'form-control', :prompt => 'All'}) %>
        <%= f.submit 'GO', :class => 'btn btn-default btn-success' %>
        <% end %>
      </div>
     
      <div class="col-md-5">
        <div class="panel panel-default panel-danger">
          <div class="panel-heading">
            <!--<button type="button" class="btn btn-default pull-right" data-toggle="modal" data-target=".modal-aidneeded">Add</button>-->
            <h3 class="panel-title">Help Needed</h3>
          </div>
          <div class="panel-body" id="demand_div">
            <%= render :partial => 'needpartial' %>
          </div>
        </div>
      </div>
      <div class="col-md-5">
        <div class="panel panel-default panel-success">
          <div class="panel-heading">
            <!--<button type="button" class="btn btn-default pull-right" data-toggle="modal" data-target=".modal-aidsupply">Add</button>-->
            <h3 class="panel-title">Help Offered</h3>
          </div>
          <div class="panel-body" id="supply_div">
            <%= render :partial => 'supplypartial' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="modal fade modal-aidneeded" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Add Alert</h4>
      </div>
      <div class="modal-body">
        <form class="form newAlert">
          <div class="form-group">
            <label class="sr-only" for="exampleInputEmail3">Name</label>
            <input type="text" class="form-control" id="" placeholder="Name & Contact Info" style="display:inline-block">
          </div>
          <div class="form-group">
            <select class="form-control">
              <option>All</option>
              <option>Food</option>
              <option>Blankets</option>
              <option>Medicines</option>
              <option>Others</option>
            </select>
          </div>
          <div class="form-group">
            <textarea class="form-control" rows="3">Details</textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-default btn-success">Submit</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade modal-aidsupply" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Add Alert</h4>
      </div>
      <div class="modal-body">
        <form class="form newAlert">
          <div class="form-group">
            <label class="sr-only" for="exampleInputEmail3">Name</label>
            <input type="text" class="form-control" id="" placeholder="Name & Contact Info" style="display:inline-block">
          </div>
          <div class="form-group">
            <select class="form-control">
              <option>All</option>
              <option>Food</option>
              <option>Blankets</option>
              <option>Medicines</option>
              <option>Others</option>
            </select>
          </div>
          <div class="form-group">
            <textarea class="form-control" rows="3">Details</textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-default btn-success">Submit</button>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        //$('#chooseItem').multiselect();
		//$('#chooseLocation').multiselect();


    });

$('#trig').on('click', function () {
    //$('#colPush').toggleClass('lftBar-0 lftBar-1');
});
 /*$('.butn-hide').on('click', function () {
    $('#colMain').toggleClass('mainCtd-1 mainCtd-0');
    $('#colPush').toggleClass('lftBar-0 lftBar-1');
});*/
</script>

app/views/posts/index.js.erb
$("#demand_div").html("<%= j (render 'needpartial') %>");
$("#supply_div").html("<%= j (render 'supplypartial') %>");
$("#city_div").html("<%= j (render 'citypartial') %>");
twttr.widgets.load();

app/views/posts/index1.html.erb
<h1>Chennai Floods </h1>
<h3> Find or Donate </h3>
<!--<table border=1>
	<tr>
		<th>
			Action
		</th>
		<th>
			Location
		</th>
		<th>
			Materials
		</th>
	</tr> -->

<div>
	<section ng-init="tab = 1">
		<ul class = 'nav nav-pills'>
			<li ng-class = "{active:tab == 1}"> 
				<a href ng-click = "tab = 1" > Needed </a>
			</li>
			<li ng-class ="{active:tab == 2}">  
				<a href ng-click = "tab = 2" > Availabe</a>
			<li>
		</ul>
	</section>
	</div>

	
	<div class="panel" ng-show = "tab === 2">
	<% @supplies.each do |supply| %>
	<blockquote class='post'>
		<p class='post_action'> Available:  </p>
		<p> @<%= supply.location %> </p>
		<ul>
		<% supply.materials.split(' ').each do |material| %>
		<li> <%= material %> </li>
		<% end %>
	</ul>
	</blockquote>
	<% end %>
	</div>
<div class="panel" ng-show = "tab === 1">
	<% @demands.each do |demand| %>
	<blockquote class='post'>
		<p class='post_action'> Needed:  </p>
		<p> @<%= demand.location %> </p>
		<ul>
		<% demand.materials.split(' ').each do |material| %>
		<li> <%= material %> </li>
		<% end %>
	</ul>
	</blockquote>
	<% end %>
</div>

<!--</table> -->

app/views/posts/location.js.erb
$("#demand_div").html("<%= j (render 'needpartial') %>");
$("#supply_div").html("<%= j (render 'supplypartial') %>");
FB.XFBML.parse(document.getElementById('demand_div'));
twttr.widgets.load();

app/views/posts/needpage.js.erb
$("#demand_div").html('');
$("#demand_div").append("<%= j (render 'needpartial') %>");
FB.XFBML.parse();
twttr.widgets.load();

app/views/posts/refresh.js.erb
$("#demand_div").html('');
$("#supply_div").html('');
$("#demand_div").append("<%= j (render 'needpartial') %>");
$("#supply_div").append("<%= j (render 'supplypartial') %>");

<% if @key == nil || @key == 'GO' %>
  $("#city_div").html("<%= j render(:partial => 'citypartial') %>");
<% end %>  
FB.XFBML.parse();
twttr.widgets.load();

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/posts/supplypage.js.erb
$("#supply_div").html('');
$("#supply_div").append("<%= j (render 'supplypartial') %>");
FB.XFBML.parse();
twttr.widgets.load();